### ISSUE TITLE
plugin not working - tips?

### ISSUE THREAD

**Issue by uover822** [senecajs/seneca-entity-history#2]
Hi,

I've got a use for this plugin in tracking/ managing entity history details but it doesn't appear to be quite working, reporting errors like:
```
[store - 42401]: {"kind":"fatal","level":600,"plugin":"seneca","tag":"3.26.2","id":"apx94ziaug79/1651101364927/42401/3.26.2/store","code":"plugin_define_failed","notice":"seneca: The definition action for the plugin entity_history has failed: seneca.fix(...).message is not a function (entity-history.js:38:10). This error is considered fatal as all plugins have to initialize correctly. You should test the plugin by itself to verify that it is working correctly. Also ensure that the configuration options passed to the plugin are correct. These are shown below under in the DETAILS section. There could also be a bug in the plugin. If you think that is the case, please create a github issue on the plugin's repository, and include this error report.","err":{"eraro":true,"orig":{},"code":"plugin_define_failed","seneca":true,"package":"seneca","msg":"seneca: The definition action for the plugin entity_history has failed: seneca.fix(...).message is not a function (entity-history.js:38:10). This error is considered fatal as all plugins have to initialize correctly. You should test the plugin by itself to verify that it is working correctly. Also ensure that the configuration options passed to the plugin are correct. These are shown below under in the DETAILS section. There could also be a bug in the plugin. If you think that is the case, please create a github issue on the plugin's repository, and include this error report.","details":{"fullname":"entity_history","message":"seneca.fix(...).message is not a function (entity-history.js:38:10)","options":{"is_finder":false,"errors":{},"ents":[],"build_who":null,"wait":false},"repo":"","errmsg":"seneca.fix(...).message is not a function","errline":"at Seneca.entity_history (/opt/msr/store/node_modules/@seneca/entity-history/dist/entity-history.js:38:10)","orig$":{},"message$":"seneca.fix(...).message is not a function"},"callpoint":"at Seneca.entity_history (/opt/msr/store/node_modules/@seneca/entity-history/dist/entity-history.js:38:10)","plugin":"entity_history","plugin_callpoint":"at Object.<anonymous> (/opt/msr/store/srv/store-dev.js:5:4)","fatal$":true},"isot":"2022-04-27T23:16:05.120Z","when":1651101365120,"level_name":"fatal","seneca_id":"apx94ziaug79/1651101364927/42401/3.26.2/store"}
```
Does anyone have experience with this plugin/ related tips? Could this be a configuration issue on my end?

Thanks

**Comment by uover822** [comment]
Hi All: Got this working :-) It seems the seneca-promisify plugin also needs to be installed/ included.
